### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by PierreRustOrange** [powerapi-ng/hwpc-sensor#18]
When stopping the sensor, I generally get a warning such as this : 

```
=================================================================
==1055067==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3174400 byte(s) in 775 object(s) allocated from:
    #0 0x7f4e13fc5720 in __interceptor_realloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe9720)
    #1 0x7f4e13e49d6e in bson_realloc (/usr/lib/x86_64-linux-gnu/libbson-1.0.so.0+0x1ed6e)

SUMMARY: AddressSanitizer: 3174400 byte(s) leaked in 775 allocation(s).
```

The sensor is running with the socket output.

**Comment by PierreRustOrange** [comment]
I thinks it grow larger the longer the sensor run. For example, after 10 min I get : 
```
=================================================================
==1055615==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 14958592 byte(s) in 3652 object(s) allocated from:
    #0 0x7fde2de72720 in __interceptor_realloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe9720)
    #1 0x7fde2dcf6d6e in bson_realloc (/usr/lib/x86_64-linux-gnu/libbson-1.0.so.0+0x1ed6e)

SUMMARY: AddressSanitizer: 14958592 byte(s) leaked in 3652 allocation(s).
```

**Comment by PierreRustOrange** [comment]
PR #21 fixes this (I tested for a few minutes and no leak was reported).
